### ISSUE TITLE
reimport on windows stucks on the "\" path separator

### ISSUE THREAD

**Issue by noncom** [zcaudate/vinyasa#15]
Hello! Thank you for the great library, I really enjoy using it!

There is one small issue that I am getting on Windows, though:

    => (./reimport)
    Compiling 9 source files to D:\work\my-project\target\classes
    warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
    1 warning
    PatternSyntaxException Unexpected internal error near index 1
    \
     ^  java.util.regex.Pattern.error (Pattern.java:1955)

apparently there is some issue with the file separator - looks like `D:\work\my-project\target\classes` gets passed in the regex pattern without a change and it thinks that `\` is for an escape sequence. I think that if you replace all "\" in the path with "/" before passing it to the regex pattern, it will work all ok, because Windows understands "this/kind/of/paths" although it uses "\this\one" by default. Also, the exact amount of "/" characters "//does////not//////really//matter", the OS will reduce them "/to/just/one" automatically.

**Comment by zcaudate** [comment]
Hey! This is an outstanding issue, here: https://github.com/zcaudate/vinyasa/issues/4. I think it's an easy fix but I don't have a windows computer. If you can get it working, please send a pr.

**Comment by noncom** [comment]
Long time, but finally I got to it.. Now I have modified the routine that gets the file separator for regexp matching... This works on MS Windows too. I have issued the pull request 16.
