### ISSUE TITLE
Option for disabling warning for using vinyasa.lein without project context.

### ISSUE THREAD

**Issue by saeidscorp** [zcaudate/vinyasa#18]
Hi, Thanks for such a great library!

Having that warning enabled by default is quite informing, But after a while just distracts me when I run a REPL! :D

Wouldn't it be helpful to provide a option in `profiles.clj` to disable this warning?
Thanks!

**Comment by zcaudate** [comment]
hmmmm... I'm just wondering why you'd want to do that (having vinyasa.lein without a project context)

it's a little dangerous and that's why the warning is there. 

but let me have a think... as it's about time a new release is made

**Comment by saeidscorp** [comment]
I don't use `vinyasa.lein` without project context! I just use the whole `vinyasa` library outside any project for other things such as pulling dependencies, reflection, etc. And every time I start the REPL this warning appears! :D

However you're right. That warning isn't such a big thing. I can change the source code for myself to provide that option. ;-)
