### ISSUE TITLE
IntelliJ/Cursive crash when profiles.clj does have reader eval macro

### ISSUE THREAD

**Issue by saeidscorp** [zcaudate/vinyasa#19]
Hi, today I realized that cursive plugin can't work with leiningen at all when I have this line in my `profiles.clj` file:

```[leiningen #=(leiningen.core.main/leiningen-version)]```

I simply removed the #= and replaced it with lein version and it got ok!

**Comment by zcaudate** [comment]
that's a nice find =) I'll leave this open... but to be honest, I'm considering nerfing the `vinyasa.lein` and `vinyasa.pull` namespaces altogether. There is a better option through [alembic](https://github.com/pallet/alembic) which does a much better job with the two current namespaces

**Comment by zcaudate** [comment]
for reference: http://z.caudate.me/revisiting-my-workflow-tooling/
