### ISSUE TITLE
Cannot run program "mv" {version: [im.chit/vinyasa "0.4.1"] os: "Windows 10 (x64)"}

### ISSUE THREAD

**Issue by rritoch** [zcaudate/vinyasa#20]
java.io.IOException: Cannot run program "mv": CreateProcess error=2, The system cannot find the file specified
 at java.lang.ProcessBuilder.start (ProcessBuilder.java:1042)
    java.lang.Runtime.exec (Runtime.java:620)
    clojure.java.shell$sh.doInvoke (shell.clj:113)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    vinyasa.reimport$reimport_compile.invoke (reimport.clj:100)
    vinyasa.reimport$reimport.doInvoke (reimport.clj:133)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    user$eval2082.invoke (form-init2944046359377625587.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6782)
    clojure.lang.Compiler.eval (Compiler.java:6745)
    clojure.core$eval.invoke (core.clj:3081)
    clojure.main$repl$read_eval_print__7099$fn__7102.invoke (main.clj:240)
    clojure.main$repl$read_eval_print__7099.invoke (main.clj:240)
    clojure.main$repl$fn__7108.invoke (main.clj:258)
    clojure.main$repl.doInvoke (main.clj:258)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    ...

**Comment by noncom** [comment]
I think this post says it well: http://stackoverflow.com/questions/17607612/equivalent-of-rm-and-mv-in-windows-cmd

**Comment by zcaudate** [comment]
Hey Ralph,

I’m tempted to bypass this as this a clojure.java.sh problem on windows 10. The solution is well known and has been documented here previously: https://github.com/zcaudate/vinyasa/issues/4 <https://github.com/zcaudate/vinyasa/issues/4>.

I thought it was fixed but I guess there are still outstanding issues. I’d be very appreciative If you could help with this problem, especially as I don’t develop on Windows machines anymore.

**Comment by rritoch** [comment]
I submitted a pull request which resolves this issue #21

**Comment by zcaudate** [comment]
thank you!
