### ISSUE TITLE
hara.reflect.pretty.classes 2.3.7 not conforming to ns spec

### ISSUE THREAD

**Issue by looselytyped** [zcaudate/vinyasa#32]
I updated my project to `[org.clojure/clojure "1.9.0-alpha12"]` and `lein repl` fails with 

```
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec:
In: [1] val: ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all] [hara.common.string :as string])) fails at: [:args] predicate: (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses),  Extra input
:clojure.spec/args  (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all] [hara.common.string :as string]))
 {:clojure.spec/problems [{:path [:args], :reason "Extra input", :pred (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses), :val ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all] [hara.common.string :as string])), :via [], :in [1]}], :clojure.spec/args (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all] [hara.common.string :as string]))}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.spec$macroexpand_check.invokeStatic(spec.clj:681)
	at clojure.spec$macroexpand_check.invoke(spec.clj:670)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
```

I believe the issue is that `vinyasa` uses `[im.chit/hara.reflect "2.3.7"]` - Looking at `hara.reflect.pretty.classes` `ns` [declaration](https://github.com/zcaudate/hara/blob/bac41f30365146bf13c5a70e32aa8380882d5856/src/hara/reflect/pretty/classes.clj#L1-L4) it indeed seems to not conform to spec. 

There was another bug fix along the same lines https://github.com/zcaudate/hara/issues/26 - and looking at `[im.chit/hara.reflect "2.4.2"]` fixes this issue. 

Thank you!!

**Comment by zcaudate** [comment]
try adding `[im.chit/hara.reflect "2.4.4"]` to your profiles.clj explicitly. That should take care of it.

**Comment by looselytyped** [comment]
Thanks @zcaudate . That's what I ended up doing. This issue was a result of that workaround. 

Would you rather I close this issue, or leave it open? 

Again, thank you for the prompt response.

**Comment by zcaudate** [comment]
glad it worked. leave it open. I'll see what I can do.

**Comment by zcaudate** [comment]
I'm in the process of integrating vinyasa into https://github.com/tahto/lucidity - where the functionality is under the `lucid.flight` namespace. If you are adventureous, try replacing vinyasa with`[tahto/lucid.flight "1.1.0"]` and adding in `profiles.clj`:

```
:injections     [(require  '[lucid.flight.inject :as inject])
                       (inject/in [lucid.flight.inject :refer [inject [in inject-in]]]
                                  [clojure.pprint pprint]
                                  [clojure.java.shell sh]
                                  [clojure.repl doc source]

                                  clojure.core
                                  [lucid.flight.reflection .& .> .? .* .% .%>]

                                  clojure.core
                                  [lucid.flight.debug :refer [[dbg-> *->] [dbg->> *->>]]])]
```
