### ISSUE TITLE
Path Issues

### ISSUE THREAD

**Issue by JacobGood1** [zcaudate/vinyasa#4]
When I try to use reimport like this
(reimport)

I get this error...

Failed: Java files did not properly compile: ["C:\\Program Files (x86)\\bombtoss\\src\\java"]
IOException CreateProcess error=2, The system cannot find the file specified  java.lang.ProcessImpl.create (ProcessImpl.java:-2)

In my leiningen I have the paths set up like this...

:source-paths ["src/clojure"]
:java-source-paths ["src/java"]

and my code is in those folders in my project.  I am using windows 7, what is wrong?

**Comment by zcaudate** [comment]
This should be fixed now.
